<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Mid2BMS.Core.Tests</RootNamespace>
    <AssemblyName>Mid2BMS.Core.Tests</AssemblyName>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendPlatformToOutputPath>false</AppendPlatformToOutputPath>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mid2BMS.Core\Mid2BMS.Core.csproj" />
  </ItemGroup>
</Project>
